# Generated by Django 4.1 on 2023-03-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chattingapp', '0005_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Gender',
            field=models.CharField(blank=True, default='Others', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_no',
            field=models.IntegerField(default=None, unique=True),
        ),
    ]
