# Generated by Django 4.1 on 2023-04-04 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chattingapp', '0007_conversation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='room_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
