# Generated by Django 4.1 on 2023-04-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chattingapp', '0010_alter_message_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
