# Generated by Django 4.1 on 2023-04-18 06:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chattingapp', '0018_alter_message_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='group_members',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=0),
        ),
        migrations.AddField(
            model_name='conversation',
            name='room_type',
            field=models.CharField(default='Normal', max_length=20),
        ),
    ]
