# Generated by Django 4.1 on 2023-04-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chattingapp', '0019_conversation_group_members_conversation_room_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='About',
            new_name='about',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Gender',
            new_name='gender',
        ),
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='otp_checking',
            name='otp_generating_count',
            field=models.IntegerField(default=3),
        ),
    ]
