# Generated by Django 4.1 on 2023-04-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chattingapp', '0020_rename_about_user_about_rename_gender_user_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='attachment',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
