# Generated by Django 4.1 on 2023-04-26 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chattingapp', '0021_alter_message_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='attachment',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
