# Generated by Django 4.1 on 2023-05-03 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chattingapp', '0024_alter_user_mobile_no_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_time', models.DateTimeField(auto_now_add=True)),
                ('ended_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_accept', models.BooleanField(default=False)),
                ('caller_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caller_history', to=settings.AUTH_USER_MODEL)),
                ('reciever_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
