# Generated by Django 4.1 on 2023-05-04 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chattingapp', '0025_callhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='Members',
        ),
        migrations.AddField(
            model_name='notifications',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
