# Generated by Django 4.1 on 2023-05-04 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chattingapp', '0026_remove_notifications_members_notifications_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='calling_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chattingapp.callhistory'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='is_calling',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='conversation_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chattingapp.conversation'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='message',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
