# Generated by Django 4.1 on 2023-05-16 10:15

import chattingapp.file_validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chattingapp', '0027_notifications_calling_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='chat_room',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='user_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('videos', models.FileField(blank=True, null=True, upload_to='status/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov']), chattingapp.file_validators.validate_video_size])),
                ('pictures', models.FileField(blank=True, null=True, upload_to='status_pictures/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'svg']), chattingapp.file_validators.validate_image_size])),
                ('text', models.CharField(blank=True, max_length=500, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
